name: Update Last.fm

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests

      - run: python main.py
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY}}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME}}

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/now-playing.svg
          git commit -m "Update Last.fm" || exit 0
          git push
